# Generated by Django 5.1.2 on 2024-10-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal_app', '0002_alter_candidate_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='company',
            field=models.ManyToManyField(related_name='candidates', to='jobportal_app.company'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='gender',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female'), ('Other', 'other')], default='Other', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=2000),
        ),
    ]
