# Generated by Django 5.1.2 on 2024-10-16 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobportal_app', '0003_alter_candidate_company_alter_candidate_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='experience',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
